version: '3.8'
services:
  mongo:
    image: mongo:6.0
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  backend:
    build: ./backend
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/taskdb
      - JWT_SECRET=supersecretjwt
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    environment:
      - VITE_API_URL=http://localhost:5000/api
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  mongo-data:
